### ISSUE TITLE
Error: Failed to initialize cloud client 'NOVA'.apiType network not found in catalog []

### ISSUE THREAD

**Issue by mgoldsworth** [yandex-qatools/teamcity-openstack-plugin#14]
Seeing an error when attempting to configure the cloud profile. It appears our provider is running an older version of OpenStack, mainly based on the Grizzly release, which may not have incorporated some network components yet, wondering if that is the issue.

Have you seen this before, and do you have any recommendations on how we can get around it?

Thank you very much!

Error:

Failed to initialize cloud client 'NOVA'.apiType network not found in catalog [] 
java.util.NoSuchElementException: apiType network not found in catalog [] 
at org.jclouds.openstack.keystone.v2_0.suppliers.LocationIdToURIFromAccessForTypeAndVersion.get(LocationIdToURIFromAccessForTypeAndVersion.java:96) 
at org.jclouds.openstack.keystone.v2_0.suppliers.LocationIdToURIFromAccessForTypeAndVersion.get(LocationIdToURIFromAccessForTypeAndVersion.java:54) 
at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:73)
at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:57)
at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) 
at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) 
at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) 
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) 
at com.google.common.cache.LocalCache.get(LocalCache.java:3934) 
at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) 
at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) 
at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.get(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:119) 
at org.jclouds.openstack.neutron.v2.functions.VersionAwareRegionToEndpoint.apply(VersionAwareRegionToEndpoint.java:55) 
at org.jclouds.openstack.neutron.v2.functions.VersionAwareRegionToEndpoint.apply(VersionAwareRegionToEndpoint.java:33) 
at org.jclouds.rest.internal.RestAnnotationProcessor.getEndpointInParametersOrNull(RestAnnotationProcessor.java:495) 
at org.jclouds.rest.internal.RestAnnotationProcessor.getEndpointFor(RestAnnotationProcessor.java:518) 
at org.jclouds.rest.internal.RestAnnotationProcessor.apply(RestAnnotationProcessor.java:188) 
at org.jclouds.rest.internal.RestAnnotationProcessor.apply(RestAnnotationProcessor.java:129) 
at org.jclouds.rest.internal.InvokeHttpMethod.toCommand(InvokeHttpMethod.java:188) 
at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:84) 
at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:73) 
at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:44) 
at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117) 
at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) 
at com.sun.proxy.$Proxy273.list(Unknown Source) 
at jetbrains.buildServer.clouds.openstack.OpenstackApi.getNetworkIdByName(OpenstackApi.java:75) 
at jetbrains.buildServer.clouds.openstack.OpenstackCloudClient.<init>(OpenstackCloudClient.java:56) 
at jetbrains.buildServer.clouds.openstack.OpenstackCloudClientFactory.createNewClient(OpenstackCloudClientFactory.java:70) 
at jetbrains.buildServer.clouds.openstack.OpenstackCloudClientFactory.createNewClient(OpenstackCloudClientFactory.java:23) 
at jetbrains.buildServer.clouds.server.impl.CloudManagerBaseImpl.createNewClient(CloudManagerBaseImpl.java:210) 
at jetbrains.buildServer.clouds.server.impl.CloudManagerBaseImpl.getClient(CloudManagerBaseImpl.java:188) 
at jetbrains.buildServer.clouds.server.impl.CloudInstancesProviderImpl.iterateInstances(CloudInstancesProviderImpl.java:45) 
at jetbrains.buildServer.clouds.server.impl.instances.RunningInstanceTrackerImpl.update(RunningInstanceTrackerImpl.java:100) 
at jetbrains.buildServer.clouds.server.impl.instances.RunningInstanceTrackerImpl$2.profilesUpdated(RunningInstanceTrackerImpl.java:86) 
at sun.reflect.GeneratedMethodAccessor3263.invoke(Unknown Source) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
at java.lang.reflect.Method.invoke(Unknown Source) 
at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:117) 
at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:67) 
at com.sun.proxy.$Proxy53.profilesUpdated(Unknown Source) 
at jetbrains.buildServer.clouds.server.impl.profile.CloudProfilePersistorImpl.reloadProfiles(CloudProfilePersistorImpl.java:117) 
at jetbrains.buildServer.clouds.server.impl.profile.CloudProfilePersistorImpl.updateProfile(CloudProfilePersistorImpl.java:101) 
at jetbrains.buildServer.clouds.server.impl.profile.CloudProfilePersontorFacade$3.run(CloudProfilePersontorFacade.java:49) 
at jetbrains.buildServer.configuration.ChangeObserver.runActionWithDisabledObserver(ChangeObserver.java:178) 
at jetbrains.buildServer.clouds.server.impl.profile.CloudProfilesWatcher.runUpdateCommand(CloudProfilesWatcher.java:42) 
at jetbrains.buildServer.clouds.server.impl.profile.CloudProfilePersontorFacade.updateProfile(CloudProfilePersontorFacade.java:47) 
at jetbrains.buildServer.clouds.server.impl.profile.SecuredCloudProfilePersistor.updateProfile(SecuredCloudProfilePersistor.java:50) 
at jetbrains.buildServer.clouds.server.web.admin.UpdateProfileAction.processProperties(UpdateProfileAction.java:52) 
at jetbrains.buildServer.clouds.server.web.admin.CloudProfileFormAction.processProfileAction(CloudProfileFormAction.java:76) 
at jetbrains.buildServer.clouds.server.web.admin.CloudAdminProfileController.processAction(CloudAdminProfileController.java:98) 
at jetbrains.buildServer.clouds.server.web.admin.CloudAdminProfileController.doPost(CloudAdminProfileController.java:92) 
at jetbrains.buildServer.clouds.server.web.admin.CloudAdminProfileController.doPost(CloudAdminProfileController.java:86) 
at jetbrains.buildServer.controllers.BaseFormXmlController$1.handleRequest(BaseFormXmlController.java:53) 
at jetbrains.buildServer.controllers.AjaxRequestProcessor.processRequest(AjaxRequestProcessor.java:45) 
at jetbrains.buildServer.controllers.BaseFormXmlController.doHandle(BaseFormXmlController.java:51) 
at jetbrains.buildServer.controllers.BaseController.handleRequestInternal(BaseController.java:75) 
at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:154) 
at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50) 
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938) 
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870) 
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961) 
at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:863) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:646) 
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) 
at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.service(TeamCityDispatcherServlet.java:11) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
at jetbrains.buildServer.web.DependencyParametersCalculationContextFilter.doFilter(DependencyParametersCalculationContextFilter.java:0) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
at jetbrains.buildServer.web.DisableSessionIdFromUrlFilter.doFilter(DisableSessionIdFromUrlFilter.java:2) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
at jetbrains.buildServer.diagnostic.web.DiagnosticFilter.doFilter(DiagnosticFilter.java:6) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
at jetbrains.buildServer.web.ResponseFragmentFilter.doFilter(ResponseFragmentFilter.java:6) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) 
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) 
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) 
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) 
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) 
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421) 
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074) 
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) 
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1739) 
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1698) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 
at java.lang.Thread.run(Unknown Source)

**Comment by GodofGurus** [comment]
Whats your hypervisor type ?

**Comment by mgoldsworth** [comment]
KVM

**Comment by xetamus** [comment]
Also seeing this issue, but definitely not running an older version of OpenStack. Were you ever able to resolve this or make some headway on it?

**Comment by mgoldsworth** [comment]
No, we did not get resolution on this at all - the response from GodofGurus above was the last communication we had.

**Comment by mgoldsworth** [comment]
In the interim, I've focused testing using the VMware plug-in. We need a workable solution - it's unfortunate we've received no further communication from the developer on this, as it likely means in order to do any testing/validation, we'll need to spend time digging into the code and debugging or just create our own plug-in.

**Comment by GodofGurus** [comment]
This plugin only supports neutron networks and not nova.
What kind of networking services are you using on your OpenStack setup ?

**Comment by xetamus** [comment]
We're using neutron and I'm able to query networks using both the REST api and the neutron client. 

That being said, I did have to specify the tenant to be able to do that, but I noticed that there is no way to actually specify the tenant in the plugin. Is this the case or am I just overlooking something?

**Comment by xetamus** [comment]
So I figured it out just now. Found the following issue with the Jenkins plugin:

https://issues.jenkins-ci.org/browse/JENKINS-28789

Turns out you need to specify username as `tenantName:userName`. As soon as I did this everything started working and I was able to spin up instances. (Just me being stupid and not following directions well it seems since I went back and looked at the example and it points this out pretty clearly)

**Comment by GodofGurus** [comment]
I ran into this as well, glad you were able to resolve it.

**Comment by mgoldsworth** [comment]
I will validate; I believe our provider had a version running nova, but most of our staff, including IT, is at a massive conference until next week. I think some updates were just made, hopefully one of those includes using neutron and we can move forward.

Thanks for your reply!

**Comment by gdahlm** [comment]
Even with neutron support this should be optional, It should not require a network name for the default network as this breaks several ml2 plugins which act differently than the base neutron configuration.

It would also be more correct to use the nova API call to capture the addresses dict vs hitting neutron directly to grab the hosts IPs.

**Comment by axel3rd** [comment]
_Oneself TODO: Try to remove [neutron usage](https://github.com/yandex-qatools/teamcity-openstack-plugin/blob/master/cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackApi.java#L75) and switch to novaApi if possible through JClouds_

**Comment by axel3rd** [comment]
> If no bump on this issue, I will close it.

So closing. Bump if necessary.
