### ISSUE TITLE
Build failed because the agent removed.

### ISSUE THREAD

**Issue by ssimsuwat** [yandex-qatools/teamcity-openstack-plugin#58]
Hi Team,

Recently our user got the build failed because of Agent removed. This problem is randomly occurred in the past until now. For your information currently we spawned the TeamCity cloud agent on Openstack with the plugin cloud-openstack v.1.2 on TeamCity Enterprise version 2020.1.4 (build 78906). From the build error log, I saw the message **Finished 2020-11-26 17:28:16 with status UNKNOWN 'Canceled (Tests failed: 5, passed: 3)'; was canceled with comment 'Agent removed'** and in the teamcity-clouds.log, I only found 2 below log messages related to the removed agent.

[2020-12-01 00:06:56,778]   INFO [stack-hk-unix 1] -  jetbrains.buildServer.clouds. - Terminating cloud openstack instance hk-unix-1606720050968

[2020-12-01 00:06:56,881]   INFO [; Flush Queue 1] - .server.impl.CloudEventsLogger - Cloud agent "hk-unix-1606720050968" {id=81582} is no longer recognized as cloud agent because instance has gone: profileId=NOVA-211, imageId=1606218173897, instanceId=1606720050968  
 
Do you have any idea why the cloud agent got terminated during running the build.

Regards,

Suriya S.

**Comment by axel3rd** [comment]
Hi @ssimsuwat, 

If the only message is this one without any other error:

```
 jetbrains.buildServer.clouds. - Terminating cloud openstack instance hk-unix-1606720050968
```

The cause probably comes from the instance status provided by OpenStack: 
- [ERROR](https://github.com/yandex-qatools/teamcity-openstack-plugin/blob/cloud-openstack-1.2/cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudInstance.java#L90)
- [SHUTOFF](https://github.com/yandex-qatools/teamcity-openstack-plugin/blob/cloud-openstack-1.2/cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudInstance.java#L93)

**Comment by aleks-90** [comment]
I have detected same behavior. Running build has been failed because of  "Agent removed".
Reason from teamcity plugin logs:

[2020-12-05 20:10:01,827]   INFO [uled executor 4] - te.IdleTimeoutTerminateFactory - Will stop instance jetbrains.buildServer.clouds.openstack.OpenstackCloudInstance@72bacaa4, profile 'RHEL7 - openstack'{id=NOVA-8, projectId=_Root} with idle time 92 minutes (idle time is 62 minutes)
[2020-12-05 20:10:01,831]   INFO [uled executor 4] - l.instances.StopInstanceAction - Terminating instance '1607158932948', profile 'RHEL7 - openstack'{id=NOVA-8, projectId=_Root}, reason: "Idle timeout reached"

why did the plugin delete the agent with active build?

**Comment by axel3rd** [comment]
@aleks-90 : Not sure that it is the same behavior than @ssimsuwat.

In your case, the removal of agent is promoted by TeamCity itself (not by the plugin) ; because detected at not used.
But yes it is strange that detected as not used if a build is really ran on it. The `with idle time 92 minutes (idle time is 62 minutes)` is quite surprising, TeamCity needs 30min to detect the idle time ... generally it is in the minute.

**Comment by aleks-90** [comment]
@axel3rd  yes, this seems to be the main reason for this build, but how can a running agent be idle?
Anyway, we got the same behavior as @ssimsuwat's description. In our case, it was a build that ran for almost 6 and a half hours and was suddenly canceled due to the removal of the agent. (Started 19 Jan 03:15 — 09:42 (6h:26m:57s)Agent:RHEL7-1611014545344).


[2021-01-19 09:41:09,917]  ERROR [enstack-RHEL7 1] -  jetbrains.buildServer.clouds. - Got exception while calculating instance status, will terminate
org.jclouds.rest.AuthorizationException: {"error": {"code": 401, "title": "Unauthorized", "message": "The request you have made requires authentication."}}
        at org.jclouds.openstack.nova.v2_0.handlers.NovaErrorHandler.handleError(NovaErrorHandler.java:99)
        at org.jclouds.http.handlers.DelegatingErrorHandler.handleError(DelegatingErrorHandler.java:65)
        at org.jclouds.http.internal.BaseHttpCommandExecutorService.shouldContinue(BaseHttpCommandExecutorService.java:138)
        at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:107)
        at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:91)
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:74)
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:45)
        at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117)
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:84)
        at com.sun.proxy.$Proxy348.get(Unknown Source)
        at jetbrains.buildServer.clouds.openstack.OpenstackCloudInstance.updateStatus(OpenstackCloudInstance.java:84)
        at jetbrains.buildServer.clouds.openstack.OpenstackCloudImage.lambda$new$0(OpenstackCloudImage.java:77)
        at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.jclouds.http.HttpResponseException: command: GET https://XXXXXX:8774/v2.1/servers/2208c612-525f-4c68-b56f-48725723d8cf HTTP/1.1 failed with response: HTTP/1.1 401 Unauthorized; content: [{"error": {"code": 401, "title": "Unauthorized", "message": "The request you have made requires authentication."}}]
        at org.jclouds.openstack.nova.v2_0.handlers.NovaErrorHandler.handleError(NovaErrorHandler.java:84)
        ... 19 more
[2021-01-19 09:41:09,918]   INFO [enstack-RHEL7 1] -  jetbrains.buildServer.clouds. - Terminating cloud openstack instance RHEL7-1611014545344
[2021-01-19 09:41:11,623]   INFO [uled executor 3] - .server.impl.CloudEventsLogger - Cloud agent "RHEL7-1611014545344" {id=2972560} is no longer recognized as cloud agent because instance has gone: profileId=NOVA-8, imageId=RHEL7, instanceId=1611014545344
[2021-01-19 09:41:11,623]   INFO [uled executor 3] - .server.impl.CloudEventsLogger - Cloud instance has gone (is not reported by cloud profile): profileId=NOVA-8, imageId=RHEL7, instanceId=1611014545344
[2021-01-19 09:42:10,936]   INFO [Ping Executor 1] - ces.terminate.AgentRemoverImpl - Removing cloud agent "RHEL7-1611014545344" {id=2972560} because: Cloud instance (id=1611014545344, imageId=RHEL7, profileId=NOVA-8) has gone (is not reported by cloud profile)

I didn't  found any problems or ERROR status  with instance. I see request to nova with 401 status and request for deletion after it.

Is there any options to fix and exclude such behavior?

**Comment by axel3rd** [comment]
> I didn't found any problems or ERROR status with instance. I see request to nova with 401 status and request for deletion after it.
> Same error with another agent with a build started on Jan 15 at 07:02 am with a duration of 3 minutes.

The http 401 error probably says a problem with the authentication token used.
If it is not global with all VMs (reproducible often), it is hard to troubleshoot this error only with this error.

**Do you have the capacity to have the logs in OpenStack side when the problem occurs ?**

There is a way to debug JClouds part in plugin, but cannot be enable via properties, you should update this code and re-package a dedicated version:

https://github.com/yandex-qatools/teamcity-openstack-plugin/blob/dff145efacce83ea2fe305618bfb88a9ee136088/cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackApi.java#L29-L32

> Is there any options to fix and exclude such behavior?

Unfortunately **no**.

The TeamCity OpenStack plugin doesn't manage directly the authentication. It is delegates to JClouds. I think a retry mechanism is implemented (but I don't have verified).

https://github.com/yandex-qatools/teamcity-openstack-plugin/blob/dff145efacce83ea2fe305618bfb88a9ee136088/cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackApi.java#L53-L54

**Comment by axel3rd** [comment]
*I allow me to close this issue, same as #62 (problem more detailed here).*
