### ISSUE TITLE
Agents are removed during build (when OpenStack problem on status)

### ISSUE THREAD

**Issue by thatstonyuknow** [yandex-qatools/teamcity-openstack-plugin#62]
Hi folks.

I've noticed that some  TeamCity agents are removed during build execution. Obviously builds are stopped and the reason is "Canceled with comment: **Agent removed**

Cloud log shows lots of  _AuthorizationException_ such as:

```
[2021-05-17 11:46:22,701] DEBUG [ck-oel8-cloud 1] - jetbrains.buildServer.clouds. - Updating instances status for openstack image: oel8-cloud
[2021-05-17 11:46:22,758] ERROR [ck-oel8-cloud 1] - jetbrains.buildServer.clouds. - {"error": {"code": 401, "title": "Unauthorized", "message": "The request you have made requires authentication."}}
org.jclouds.rest.AuthorizationException: {"error": {"code": 401, "title": "Unauthorized", "message": "The request you have made requires authentication."}}
.........

Caused by: org.jclouds.http.HttpResponseException: command: GET https://nova-public-eu1.mycompany.com:8774/v2.1/servers/detail HTTP/1.1 failed with response: HTTP/1.1 401 Unauthorized; content: [{"error": {"code": 401, "title": "Unauthorized", "message": "The request you have made requires authentication."}}]
        at org.jclouds.openstack.nova.v2_0.handlers.NovaErrorHandler.handleError(NovaErrorHandler.java:84)
        ... 18 more
```

Related _nova_ logs:

```
2021-05-17 11:46:22.758 2150 WARNING keystonemiddleware.auth_token [-] Authorization failed for token: keystonemiddleware.auth_token._exceptions.InvalidToken: Token authorization failed
2021-05-17 11:46:22.759 2150 INFO nova.osapi_compute.wsgi.server [-] 10.10.10.24 "GET /v2.1/servers/detail HTTP/1.1" status: 401 len: 452 time: 0.0441337
```

_Keystone_:
```2021-05-17 11:46:22.755 499988 WARNING keystone.server.flask.application [req-0dbdb892-2a62-4f8e-a62e-1e5ceafa2757 cfc25c8df63d4d2d9c8beaf6e1c772bd 80025f5dbccf44b181892be7c1f70b99 - default default] Failed to validate token: keystone.exception.TokenNotFound: Failed to validate token```

I've noticed that 401 unauth exceptions repeat each 8 hours what coincides with a moment of changing tokens.
Found similar comments as well here: [401 unauth error](https://github.com/yandex-qatools/teamcity-openstack-plugin/issues/58#issuecomment-763019685)

@aleks-90  please confirm if you observed the same

Plugin ver 1.5
TeamCity  ver 2020.1.5 

Could you please have a look and assist ? Feel free to ask more info if required.

**Comment by thatstonyuknow** [comment]
Hi @axel3rd 

Here is the result of debug:

**First time 401:**

```
[2021-05-21 08:02:59,940]  DEBUG [k-rhel8-cloud 1] -  jetbrains.buildServer.clouds. - Updating instances status for openstack image: rhel8-cloud
[2021-05-21 08:02:59,940]  DEBUG [k-rhel8-cloud 1] - rest.internal.InvokeHttpMethod - >> invoking server:list
[2021-05-21 08:02:59,941]  DEBUG [k-rhel8-cloud 1] - aUrlHttpCommandExecutorService - Sending request -1066236722: GET https://nova-public-eu1.mycompanygroup.com:8774/v2.1/servers/detail HTTP/1.1
[2021-05-21 08:02:59,979]  DEBUG [k-rhel8-cloud 1] - aUrlHttpCommandExecutorService - Receiving response -1066236722: HTTP/1.1 401 Unauthorized
[2021-05-21 08:02:59,979]  DEBUG [k-rhel8-cloud 1] -                   jclouds.wire - << "{"error": {"code": 401, "title": "Unauthorized", "message": "The request you have made requires authentication."}}"
[2021-05-21 08:02:59,980]  DEBUG [k-rhel8-cloud 1] - one.auth.handlers.RetryOnRenew - invalidating authentication token - first time for [method=org.jclouds.openstack.nova.v2_0.features.ServerApi.public abstract org.jclouds.collect.PagedIterable org.jclouds.openstack.nova.v2_0.features.ServerApi.listInDetail()[], request=GET https://nova-public-eu1.mycompanygroup.com:8774/v2.1/servers/detail HTTP/1.1]
[2021-05-21 08:02:59,982]  DEBUG [k-rhel8-cloud 1] - rest.internal.InvokeHttpMethod - >> invoking V3AuthenticationApi.authenticatePassword
[2021-05-21 08:02:59,982]  DEBUG [k-rhel8-cloud 1] - aUrlHttpCommandExecutorService - Sending request 1647924420: POST https://cloud.mycompanygroup.com:5000/v3/auth/tokens HTTP/1.1
[2021-05-21 08:02:59,982]  DEBUG [k-rhel8-cloud 1] -                   jclouds.wire - >> "{"auth":{"identity":{"methods":["password"],"password":{"user":{"name":"teamcity","domain":{"name":"mycompanygroup.com"},"password":"xxxxxxxxxxxxxx"}}},"scope":{"project":{"name":"teamcity","domain":{"name":"mycompanygroup.com"}}}}}"
```


**_First retry:_**

```
[2021-05-21 08:03:00,020]  DEBUG [k-rhel8-cloud 1] - aUrlHttpCommandExecutorService - Sending request -433664936: GET https://nova-public-eu1.mycompanygroup.com:8774/v2.1/servers/detail HTTP/1.1
[2021-05-21 08:03:00,249]  DEBUG [ts'{id=vmw-1} 3] - nnector.CloudAsyncTaskExecutor - Check Tasks processed 0 tasks in 0 ms.
[2021-05-21 08:03:00,359]  DEBUG [k-rhel7-cloud 1] -  jetbrains.buildServer.clouds. - Updating instances status for openstack image: rhel7-cloud
[2021-05-21 08:03:00,359]  DEBUG [k-rhel7-cloud 1] - rest.internal.InvokeHttpMethod - >> invoking server:list
[2021-05-21 08:03:00,359]  DEBUG [k-rhel7-cloud 1] - aUrlHttpCommandExecutorService - Sending request 1132514096: GET https://nova-public-eu1.mycompanygroup.com:8774/v2.1/servers/detail HTTP/1.1
[2021-05-21 08:03:00,380]  DEBUG [k-rhel7-cloud 1] - aUrlHttpCommandExecutorService - Receiving response 1132514096: HTTP/1.1 401 Unauthorized
[2021-05-21 08:03:00,381]  DEBUG [k-rhel7-cloud 1] -                   jclouds.wire - << "{"error": {"code": 401, "title": "Unauthorized", "message": "The request you have made requires authentication."}}"
[2021-05-21 08:03:00,381]  DEBUG [k-rhel7-cloud 1] - one.auth.handlers.RetryOnRenew - invalidating authentication token - retry 1 for [method=org.jclouds.openstack.nova.v2_0.features.ServerApi.public abstract org.jclouds.collect.PagedIterable org.jclouds.openstack.nova.v2_0.features.ServerApi.listInDetail()[], request=GET https://nova-public-eu1.mycompanygroup.com:8774/v2.1/servers/detail HTTP/1.1]
```

**_Second retry:_**

```
[2021-05-21 08:03:00,402]  DEBUG [ck-win-kasper 1] -  jetbrains.buildServer.clouds. - Updating instances status for openstack image: win-kasper
[2021-05-21 08:03:00,402]  DEBUG [ck-win-kasper 1] - rest.internal.InvokeHttpMethod - >> invoking server:list
[2021-05-21 08:03:00,402]  DEBUG [ck-win-kasper 1] - aUrlHttpCommandExecutorService - Sending request -432876981: GET https://nova-public-eu1.mycompanygroup.com:8774/v2.1/servers/detail HTTP/1.1
[2021-05-21 08:03:00,416]  DEBUG [ck-win-kasper 1] - aUrlHttpCommandExecutorService - Receiving response -432876981: HTTP/1.1 401 Unauthorized
[2021-05-21 08:03:00,416]  DEBUG [ck-win-kasper 1] -                   jclouds.wire - << "{"error": {"code": 401, "title": "Unauthorized", "message": "The request you have made requires authentication."}}"
[2021-05-21 08:03:00,416]  DEBUG [ck-win-kasper 1] - one.auth.handlers.RetryOnRenew - invalidating authentication token - retry 2 for [method=org.jclouds.openstack.nova.v2_0.features.ServerApi.public abstract org.jclouds.collect.PagedIterable org.jclouds.openstack.nova.v2_0.features.ServerApi.listInDetail()[], request=GET https://nova-public-eu1.mycompanygroup.com:8774/v2.1/servers/detail HTTP/1.1]
```


**_Third retry:_**
```


[2021-05-21 08:03:00,704]  DEBUG [centos7-cloud 1] -  jetbrains.buildServer.clouds. - Updating instances status for openstack image: centos7-cloud
[2021-05-21 08:03:00,704]  DEBUG [centos7-cloud 1] - rest.internal.InvokeHttpMethod - >> invoking server:list
[2021-05-21 08:03:00,705]  DEBUG [centos7-cloud 1] - aUrlHttpCommandExecutorService - Sending request -1838007161: GET https://nova-public-eu1.mycompanygroup.com:8774/v2.1/servers/detail HTTP/1.1
[2021-05-21 08:03:00,711]  DEBUG [centos7-cloud 1] - aUrlHttpCommandExecutorService - Receiving response -1838007161: HTTP/1.1 401 Unauthorized
[2021-05-21 08:03:00,711]  DEBUG [centos7-cloud 1] -                   jclouds.wire - << "{"error": {"code": 401, "title": "Unauthorized", "message": "The request you have made requires authentication."}}"
[2021-05-21 08:03:00,711]  DEBUG [centos7-cloud 1] - one.auth.handlers.RetryOnRenew - invalidating authentication token - retry 3 for [method=org.jclouds.openstack.nova.v2_0.features.ServerApi.public abstract org.jclouds.collect.PagedIterable org.jclouds.openstack.nova.v2_0.features.ServerApi.listInDetail()[], request=GET https://nova-public-eu1.mycompanygroup.com:8774/v2.1/servers/detail HTTP/1.1]
[2021-05-21 08:03:00,849]  DEBUG [ts'{id=vmw-1} 3] - nnector.CloudAsyncTaskExecutor - Check Tasks processed 0 tasks in 0 ms.
```


**_Give up_**

```
2021-05-21 08:03:01,476]  DEBUG [in-2019-cloud 1] -  jetbrains.buildServer.clouds. - Updating instances status for openstack image: win-2019-cloud
[2021-05-21 08:03:01,477]  DEBUG [in-2019-cloud 1] - rest.internal.InvokeHttpMethod - >> invoking server:list
[2021-05-21 08:03:01,477]  DEBUG [in-2019-cloud 1] - aUrlHttpCommandExecutorService - Sending request 2042874021: GET https://nova-public-eu1.mycompanygroup.com:8774/v2.1/servers/detail HTTP/1.1
[2021-05-21 08:03:01,493]  DEBUG [in-2019-cloud 1] - aUrlHttpCommandExecutorService - Receiving response 2042874021: HTTP/1.1 401 Unauthorized
[2021-05-21 08:03:01,493]  DEBUG [in-2019-cloud 1] -                   jclouds.wire - << "{"error": {"code": 401, "title": "Unauthorized", "message": "The request you have made requires authentication."}}"
[2021-05-21 08:03:01,493]  DEBUG [in-2019-cloud 1] - one.auth.handlers.RetryOnRenew - too many 401s - giving up after: 4 for [method=org.jclouds.openstack.nova.v2_0.features.ServerApi.public abstract org.jclouds.collect.PagedIterable org.jclouds.openstack.nova.v2_0.features.ServerApi.listInDetail()[], request=GET https://nova-public-eu1.mycompanygroup.com:8774/v2.1/servers/detail HTTP/1.1]
[2021-05-21 08:03:01,522]  ERROR [in-2019-cloud 1] -  jetbrains.buildServer.clouds. - {"error": {"code": 401, "title": "Unauthorized", "message": "The request you have made requires authentication."}}
org.jclouds.rest.AuthorizationException: {"error": {"code": 401, "title": "Unauthorized", "message": "The request you have made requires authentication."}}
	at org.jclouds.openstack.nova.v2_0.handlers.NovaErrorHandler.handleError(NovaErrorHandler.java:99)
	at org.jclouds.http.handlers.DelegatingErrorHandler.handleError(DelegatingErrorHandler.java:65)
	at org.jclouds.http.internal.BaseHttpCommandExecutorService.shouldContinue(BaseHttpCommandExecutorService.java:138)
	at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:107)
	at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:91)
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:74)
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:45)
	at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:84)
	at com.sun.proxy.$Proxy370.listInDetail(Unknown Source)
	at jetbrains.buildServer.clouds.openstack.OpenstackCloudImage.lambda$new$1(OpenstackCloudImage.java:95)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:190)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jclouds.http.HttpResponseException: command: GET https://nova-public-eu1.mycompanygroup.com:8774/v2.1/servers/detail HTTP/1.1 failed with response: HTTP/1.1 401 Unauthorized; content: [{"error": {"code": 401, "title": "Unauthorized", "message": "The request you have made requires authentication."}}]
	at org.jclouds.openstack.nova.v2_0.handlers.NovaErrorHandler.handleError(NovaErrorHandler.java:84)
	... 18 more
```


**_And finally multiple attempts to delete agents_**

```
[2021-05-21 08:03:01,525]  DEBUG [in-2019-cloud 1] -  jetbrains.buildServer.clouds. - Set status for openstack instance win-2019-cloud-1621492711724: null (previous was: Running)
[2021-05-21 08:03:01,525]   INFO [in-2019-cloud 1] -  jetbrains.buildServer.clouds. - Terminating cloud openstack instance win-2019-cloud-1621492711724
[2021-05-21 08:03:01,527]  DEBUG [in-2019-cloud 1] - rest.internal.InvokeHttpMethod - >> invoking server:delete
[2021-05-21 08:03:01,527]  DEBUG [in-2019-cloud 1] - aUrlHttpCommandExecutorService - Sending request 1577808029: DELETE https://nova-public-eu1.mycompanygroup.com:8774/v2.1/servers/0c7117cb-2232-4882-a177-489de0b1b41c HTTP/1.1
[2021-05-21 08:03:01,533]  DEBUG [in-2019-cloud 1] - aUrlHttpCommandExecutorService - Receiving response 1577808029: HTTP/1.1 401 Unauthorized
```

**Comment by amix307** [comment]
Have the same problem, bro! This looks like we're getting somewhere.

**Comment by axel3rd** [comment]
👋 @thatstonyuknow,

Thanks for the details, we can see that JClouds component deals correctly with authentication retry, so I'm surprised about the 401. 
If login/password are correct and OpenStack responses "not authorized", it will be hard todo something ... updating VMs status is required 😢.

Checking the logs I see multiple OpenStack images:

```
rhel8-cloud
rhel7-cloud
win-kasper
centos7-cloud
win-2019-cloud
```

**Question 1**: Is it only one cloud-profile definition with multiple images defined (as in [documentation](https://github.com/yandex-qatools/teamcity-openstack-plugin#server-configuration)) **or** it is multiple cloud-profiles definition (with one image for each) ?

**Question 2**: When the problem occurs, only agents after 8 hours are concerned (VM status KO => try to delete KO => remove from list) and some VMs continue to be OK (authentication problem is not global in this case) ? **or** authentication problem is global and all VMs are removed (due to status & delete fail)

**Comment by thatstonyuknow** [comment]
@axel3rd 

1. I have multiple profiles for each cloud image.
2. You know, I haven't checked all instances. Not sure but looks like some Vms are still ok after issue appears. I'm about to set up devs env and  reproduce the issue.

**Comment by paksv** [comment]
Hi, I was again requested to share some thoughts on this :)
I would probably move the following snippet (lines 103-108) in  `OpenstackCloudImage` under the try block, so update only occurs if status update is successful (when an `errorInfo` for an image is not null, TC doesn't deal with instances anyway)
```            
            for (OpenstackCloudInstance instance : getInstances()) {
                instance.updateStatus(status.get(instance.getName()));
                if (instance.getStatus() == InstanceStatus.STOPPED || instance.getStatus() == InstanceStatus.ERROR) {
                    forgetInstance(instance);
                }
            }
```
Looks like this can be a cause of occasional terminations, if the `Map<String, Server.Status> status` is not populated properly.

**Comment by axel3rd** [comment]
👋 @paksv,

Many thanks for the catch and the improvement proposal (I will try to have a look shortly).
Unfortunately, if the root cause is openstack side (some response with an authentication problem on classic request), long time impacts are always present (sample: Agents never removed).

**Comment by axel3rd** [comment]
The `UNKNOWN` status (avoiding un-wanted termination) implementation is done in SNAPSHOT: **[cloud-openstack.zip](https://teamcity.jetbrains.com/repository/download/TeamCityThirdPartyPlugins_OpenStackCloudSupport_PullRequestAnalysis/3509094:id/cloud-openstack.zip)**.

**Note**: The root cause (communication problem  with OpenStack) are not fixed => some impacts occurs again (sample: TeamCity plugibn could perhaps not stop some VM => They are staying into OpenStack instances list).

@thatstonyuknow / @amix307 : If you could test on your DEV platform, to verify the behavior is better than previously, it would be nice 😗.

**Comment by thatstonyuknow** [comment]
@paksv  thanks for looking into
@axel3rd  I'll  test it and get back asap
Thanks

**Comment by axel3rd** [comment]
@thatstonyuknow : Before and after plugin deployment, can you say me if you see or not the OpenStack pool in the http://teamcity.host.com/agents/overview and your TeamCity version ... because on TeamCity 2021.1 (my dev platform), I lost the visibility (even if it is working fine when agent are up):

![image](https://user-images.githubusercontent.com/2912441/121356264-fa4e9800-c930-11eb-89ff-f85ba5c82933.png)

I think it is more related to Sakura UI (so another issue to create), but any feedback is welcome.

**Comment by axel3rd** [comment]
Snapshot version: [cloud-openstack.zip](https://teamcity.jetbrains.com/repository/download/TeamCityThirdPartyPlugins_OpenStackCloudSupport_BuildSnapshotIntegration/3540665:id/cloud-openstack.zip) (**v1.6**).

**Comment by axel3rd** [comment]
Release **v1.6** done: [cloud-openstack.zip](https://teamcity.jetbrains.com/repository/download/TeamCityThirdPartyPlugins_OpenStackCloudSupport_Release/3561870:id/cloud-openstack.zip)
